import Head from 'next/head';
import Image from 'next/image';
import ConnectWalletGrid from '../components/ConnectWalletGrid';
import SmartContractGrid from '../components/SmartContractGrid';
import styles from '../styles/Home.module.css';
import { useWeb3React } from '@web3-react/core';


export default function Home() {

  const {active} = useWeb3React();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Relayer
        </h1>
        <ConnectWalletGrid/>
        {active && <SmartContractGrid/>}

      </main>
    </div>
  )
}
